lzc-sdk-version: "0.1"
name: Zen
package: cloud.lazycat.app.zen
version: 0.1.0
description: Minimal Notes App
homepage: https://github.com/sheshbabu/zen
author: sheshbabu
application:
  subdomain: zen
  background_task: true
  public_path:
    - /
  routes:
    - /=http://zen:8080/
services:
  zen:
    image: registry.lazycat.cloud/czyt/sheshbabu/zen/zen:cfd87b4412f3663e
    environment:
      - DATA_FOLDER=/data
      - IMAGES_FOLDER=/images
      - PORT=8080

    binds:
      - /lzcapp/var/data:/data
      - /lzcapp/var/images:/images
